### ISSUE TITLE
npm run dev will always host an "old" instance of the server

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil-dev-server#21] opened 2018-01-29 09:27 UTC
Hi,

I have cloned https://github.com/ionic-team/stencil-component-starter to try something. I had previously (some days ago) cloned a different Stencil repo.

Now when I npm run dev the component-starter I get the content of the "old" project I was running a few days ago. The URL is http://localhost:3333/

Changing the port using --httpPort is not working. Still routing me to 3333.

Displayed component (old component):
![bildschirmfoto 2018-01-29 um 10 26 25](https://user-images.githubusercontent.com/6666636/35502949-f0c30970-04de-11e8-9a1e-3851a2b88fae.png)

Desired content (new component):
![bildschirmfoto 2018-01-29 um 10 26 40](https://user-images.githubusercontent.com/6666636/35502953-f3602b54-04de-11e8-833b-d0211eed77e6.png)

EDIT:
There is definitely only running the new server. I have reboot in between.... But somehow this "keeps being hosted"?

Any ideas?

**Comment by jgw96** [comment] 2018-02-19 17:04
Hello! This was caused by a bug with our pre-rendering in Stencil. This has since been fixed in the latest releases (: . Thanks for using Stencil!

**Closed by jgw96** 2018-02-19 17:04 UTC
