### ISSUE TITLE
404s Hang

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil-dev-server#13] opened 2017-09-15 13:57 UTC
Any file that doesn't actually exist does not return a 404.

**Comment by jthoms1** [comment] 2017-10-04 15:17
This might be fixed in a new release.  I am unable to reproduce the issue.

**Comment by jthoms1** [comment] 2017-10-20 19:19
This is resolved with commit 348b6a59a419eda77f5fe13fd3fbf1ea715ca771.

**Closed by jthoms1** 2017-10-20 19:19 UTC
Labels: response needed
